#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Update index.md script for LLM Wiki.
Creates and updates the wiki/index.md file with links to all wiki pages.
"""

import os
import sys
import yaml
from datetime import datetime

# Set default encoding to UTF-8
sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')


def load_config() -> dict:
    """Load configuration from config.yaml"""
    config_path = os.path.join(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")), "config.yaml")
    with open(config_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def get_all_wiki_pages(wiki_dir: str) -> dict:
    """
    Get all wiki pages organized by type
    
    Returns:
        dict: {"concepts": [...], "entities": [...], "summaries": [...]}
    """
    pages = {"concepts": [], "entities": [], "summaries": []}
    
    for root, dirs, files in os.walk(wiki_dir):
        for file in files:
            if file.endswith(".md") and file != "index.md":
                relative_path = os.path.relpath(os.path.join(root, file), wiki_dir)
                page_name = os.path.splitext(relative_path.replace(os.path.sep, "/"))[0]
                
                # Determine page type based on directory
                if "concepts" in relative_path:
                    pages["concepts"].append(page_name)
                elif "entities" in relative_path:
                    pages["entities"].append(page_name)
                elif "summaries" in relative_path:
                    pages["summaries"].append(page_name)
    
    # Sort pages alphabetically
    for key in pages:
        pages[key].sort()
    
    return pages


def generate_index_content(pages: dict) -> str:
    """
    Generate index.md content
    """
    # Generate sections first
    concepts_section = "" if not pages["concepts"] else "\n".join([f"- [[{p}]]" for p in pages["concepts"]])
    entities_section = "" if not pages["entities"] else "\n".join([f"- [[{p}]]" for p in pages["entities"]])
    summaries_section = "" if not pages["summaries"] else "\n".join([f"- [[{p}]]" for p in pages["summaries"]])
    
    now = datetime.now().isoformat()
    
    content = f"""---
title: LLM Wiki Index
description: Index of all wiki pages
created: {now}
updated: {now}
---

# LLM Wiki Index

Welcome to the LLM Wiki knowledge base. This index provides an overview of all available pages.

## Concepts

Concepts are abstract ideas or principles with detailed definitions and explanations.

{concepts_section}

## Entities

Entities are specific people, organizations, models, technologies, or places with descriptions and relevance.

{entities_section}

## Summaries

Summaries are extracted from original source documents, providing key insights and references.

{summaries_section}

## About

This index is automatically generated by the LLM Wiki system. Last updated: {now}
"""
    
    return content


def main():
    """Main function"""
    config = load_config()
    wiki_dir = config.get("wiki_dir", "wiki")
    index_file = os.path.join(wiki_dir, "index.md")
    
    # Create wiki directory if it doesn't exist
    os.makedirs(wiki_dir, exist_ok=True)
    
    # Get all wiki pages
    pages = get_all_wiki_pages(wiki_dir)
    
    # Generate index content
    content = generate_index_content(pages)
    
    # Write index file
    with open(index_file, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"[OK] Updated index.md with {len(pages['concepts'])} concepts, {len(pages['entities'])} entities, {len(pages['summaries'])} summaries")
    print(f"Index file saved to: {index_file}")


if __name__ == "__main__":
    main()